### PR TITLE
Add package.json so it can be pushed to npm

### PR DESCRIPTION
**Pull request by jaapz**

### CODE REVIEW

**Comment by jaapz** [comment]
@highslide-software thanks for merging this in, could you also publish the package to npm?

**Comment by jaapz** [comment]
@TorsteinHonsi could you plese publish this package to npm?

**Comment by TorsteinHonsi** [comment]
It's done! https://www.npmjs.com/package/highcharts-draggable-points

Version 2.0 also added CommonJS support on the same pattern as Highcharts modules.

```js
var Highcharts = require('highcharts');
require('highcharts-draggable-points')(Highcharts);
```

**Comment by jaapz** [comment]
Thanks!

**Pull request merged**
